from pathlib import Path
from datetime import datetime

import geopandas as gpd

from .ai import draft_text
from .config import PipelineConfig
from .logging_config import setup_logging
from .rag import retrieve_snippets


logger = setup_logging(__name__)


def _build_base_prompt(config: PipelineConfig) -> str:
  base = (
    "Draft a short, neutral summary of a generic geospatial field data collection "
    "campaign suitable for a certification/monitoring report. Do not reference any "
    "private or project-specific data; keep the description high-level and abstract."
  )

  if not config.rag_enabled:
    return base

  snippets = retrieve_snippets(
    query="monitoring reporting plan land use forests safeguarding validation verification",
    docs_dir=config.rag_docs_dir,
    top_k=config.rag_top_k,
  )
  if not snippets:
    return base

  joined = "\n\n".join(f"[{s.doc_name}]\n{s.text}" for s in snippets)
  return (
    base
    + "\n\nUse the following excerpts from standard/MRV documents as inspiration, "
    + "but still keep the summary generic and not project-specific:\n\n"
    + joined
  )


def generate_report(
  gpkg_path: Path, config: PipelineConfig, output_md: Path, mode: str = "internal"
) -> Path:
  """
  Generate a Markdown report.

  mode:
    - "internal": AI narrative embedded in the report (for internal use only).
    - "submission": AI suggestions, if any, are written to a separate *_ai_notes.md
      file; the main report remains AI-safe and is intended for external use.
  """
  layer = config.main_layer
  gdf = gpd.read_file(gpkg_path, layer=layer)

  n_features = len(gdf)
  crs = gdf.crs
  ts = datetime.utcnow().isoformat() + "Z"

  intro = (
    f"# Field data report\n\n"
    f"- Source GeoPackage: `{gpkg_path}`\n"
    f"- Layer: `{layer}`\n"
    f"- Features: **{n_features}**\n"
    f"- CRS: `{crs}`\n"
    f"- Generated at: `{ts}` (UTC)\n\n"
  )

  base_prompt = _build_base_prompt(config)

  if mode == "internal":
    if config.ai_enabled and config.ai_provider:
      ai_paragraph = draft_text(base_prompt, provider=config.ai_provider)
    else:
      ai_paragraph = draft_text(base_prompt, provider=None)
    body = ai_paragraph + "\n"
  else:
    # Submission mode: keep main report AI-safe, optionally write AI notes separately.
    body = (
      "This report is intended for external submission. Narrative sections must be "
      "completed and reviewed by project staff based on verifiable evidence and the "
      "applicable Gold Standard documents.\n\n"
    )
    if config.ai_enabled and config.ai_provider:
      notes = draft_text(base_prompt, provider=config.ai_provider)
      notes_path = output_md.with_name(output_md.stem + "_ai_notes.md")
      notes_md = (
        "# AI-assisted draft notes (internal use only)\n\n"
        "The following text is generated by an AI model and is provided solely as "
        "draft material. It must not be used as evidence or submitted without "
        "human review and editing.\n\n"
        + notes
        + "\n"
      )
      notes_path.write_text(notes_md, encoding="utf-8")
      logger.info("AI draft notes written to %s", notes_path)

  md = intro + body

  output_md.parent.mkdir(parents=True, exist_ok=True)
  output_md.write_text(md, encoding="utf-8")
  logger.info("Report written to %s", output_md)
  return output_md

